### ISSUE TITLE
Feature request: logging routines

### ISSUE THREAD

**Issue by execveat** [sigoden/runme#3]
Hi there and thanks for a great tool! I'd like to propose a convenience functions for logging to stdout and stderr. Those would be useful for logging output in situation when regular stdout/stderr get redirected by caller function:

```bash
deeply-nested() {
  echo "Write log messages to stdout" | log_info
  echo "Write warnings to stderr" | log_err
  
  actual-output-top-level-expects
}

# @cmd
top-level() {
  result=$(deeply-nested 2>&1)
  do-something $result
}
```

**Comment by execveat** [comment]
~~Ah, turns out it's as easy as~~

```bash
LOG=/dev/stdout
ERROR=/dev/stderr

deeply-nested() {
  echo "Write log messages to stdout" >$LOG
  echo "Write warnings to stderr" >$ERROR
}
```

~~Maybe just add it to examples.~~

EDIT: This doesn't work at all, not sure what I was thinking. So yeah, having some kind of built-in logging framework would be nice.

**Comment by execveat** [comment]
This seems to work for me:

```bash
exec 3>&1
exec 4>&2

log() {
  cat - >&3
}

err() {
  cat - >&4
}
```

but it depends on nothing else messing with 3 and 4. Named descriptors don't work for some reason:

```bash
exec {original_stdout}>&1
exec {original_stderr}>&2

log() {
  cat - >&${original_stdout}
}

err() {
  cat - >&${original_stderr}
}
```

Did I mess something?

**Comment by sigoden** [comment]
The logs should be handled by the shell script itself. 

your solution is great.
