### ISSUE TITLE
BUG: Task arguments are treated as unique

### ISSUE THREAD

**Issue by execveat** [sigoden/runme#4]
There is an argument collision. It seems that runme expects task arguments to be unique. As a demonstration, the following example called as `runme test` outputs 'test' which is incorrect. Inside b() `$argc_var` is not equal to `$1`.

```
# @cmd
# @arg var!
a() {
  b BLA BLA BLA
}

# @cmd
# @arg var!
b() {
  echo "$argc_var"
}

eval $(runme --runme-eval "$0" "$@")
```

**Comment by sigoden** [comment]
The usage of `@arg` is described in detail in [argc](https://github.com/sigoden/argc#arg]) .

`@arg var!` take only one argument. you need to use `@arg var+` for more arguments.

```diff
#!/usr/bin/env bash

set -e

# @cmd
a() {
-  b BLA BLA BLA
+  runme b BLA BLA BLA
}

# @cmd
-# @arg var!
+# @arg var*
b() {
  echo $argc_var
}

-eval $(runme --runme-eval "$0" "$@")
+eval "$(runme --runme-eval "$0" "$@")"
```

By the way, you can use positional variables like `$1`, `$*` `$@` in task function。
